# -*- coding: utf-8 -*-
"""seaborn_foundations.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EouFlqaP2CtJKNhvwkxMngH2-0ItKZcB
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# %matplotlib inline
# %reload_ext autoreload
# %autoreload 2

print(sns.get_dataset_names())

df = sns.load_dataset('car_crashes')
df

#Distribution Plot:
sns.distplot(df['not_distracted'])

sns.distplot(df['not_distracted'],kde = False, bins = 25)

#Joint PLot:
sns.jointplot(x = 'speeding', y ='alcohol', data = df, kind = 'reg')

sns.jointplot(x = 'speeding', y ='alcohol', data = df, kind = 'kde')

sns.jointplot(x = 'speeding', y ='alcohol', data = df, kind = 'hex')

#KDE plot:
sns.kdeplot(df['alcohol'])

#Pair Plots:
sns.pairplot(df)

tips_df = sns.load_dataset('tips')
tips_df

sns.pairplot(tips_df,hue = 'sex', palette = "Blues")

#Rug plot:
sns.rugplot(tips_df['tip'])

#Styling:
sns.set_style('ticks')
plt.figure(figsize = (8,4))
sns.set_context('talk',font_scale =1.4)

sns.jointplot(x='speeding',y = 'alcohol', data = df, kind = 'reg')

sns.despine(left = False,bottom = True)

#Categorical Plots:


 #Bar plot:
 sns.barplot(x = 'sex',y ='total_bill',data = tips_df)

#Count Plot:

sns.countplot(x = 'sex',data = tips_df)

#Box Plot:
sns.boxplot(x ='day',y = 'total_bill', data = tips_df,hue = 'sex')
plt.legend(loc = 0)

#Violin Plot:
sns.violinplot(x = 'day', y = 'total_bill', data = tips_df,hue = 'sex', split = True)
plt.legend(loc = 0)

#Strip Plots:
plt.figure(figsize=(8,4))
sns.stripplot(x = 'day',y = 'total_bill',data = tips_df,jitter = True ,hue = 'sex',dodge = True)

#Swarm Plots:
sns.violinplot(x = 'day', y = 'total_bill', data = tips_df)
sns.swarmplot(x = 'day', y = 'total_bill', data = tips_df,color = 'white')

